# Generated by Django 5.1.3 on 2024-11-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_create', 'Can add a new book'), ('can_delete', 'can delete an existing book')]},
        ),
    ]
