# Generated by Django 5.1.2 on 2024-11-28 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0004_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
