# Generated by Django 5.1.2 on 2024-11-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0007_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': []},
        ),
    ]
