# Generated by Django 5.1.2 on 2024-11-28 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0008_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_create', 'Can add a new book'), ('can_view', 'Can view any book'), ('can_edit', 'Can edit a book'), ('can_delete', 'Can delete any book')]},
        ),
    ]
