# Generated by Django 5.1.2 on 2024-11-16 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'can add a new book'), ('can_change_book', 'can edit the existing book'), ('can_delete_book', 'can delete any book')]},
        ),
    ]
