# Generated by Django 5.1.3 on 2024-12-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0005_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Member', 'Member'), ('Librarian', 'Librarian')], default='Member', max_length=10),
        ),
    ]
